name: Terraform and Docker Deployment
on:
  workflow_call:  # Called by other repositories
    inputs:
      environment:
        required: true
        type: string
      enable_docker:
        required: false
        type: boolean
        default: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false
  workflow_dispatch:  # Manually trigger this workflow in infrastructure-repo
    inputs:
      environment:
        required: true
        type: string
        default: 'dev'
      enable_docker:
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve -var="environment=${{ inputs.environment }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      # Docker build and push steps (only run if enable_docker is true)
      - name: Set up Docker Buildx
        if: inputs.enable_docker
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        if: inputs.enable_docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        if: inputs.enable_docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:${{ inputs.environment }}
