name: Terraform & Docker Deployment

on:
  workflow_call:  # Called by app-repo
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

  workflow_dispatch:  # Manually trigger this workflow in infrastructure-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve -var="environment=${{ inputs.environment }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract Git Commit SHA
        id: get_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
      - name: Build and Push Docker Image
        run: |
          docker build -t mydockerhub/myapp:${{ env.sha }} -t mydockerhub/myapp:latest .
          docker push mydockerhub/myapp:${{ env.sha }}
          docker push mydockerhub/myapp:latest
